### PR TITLE
Fixing the schema comparison for patching

### PR DESCRIPTION
**Pull request by byapparov**
Patching was not working when description changed for a given field

### CODE REVIEW

**Comment by dankruse1** [comment]
If i understand this change correctly you are adding the bqMatchField function to compare just the field name and field type values opposed to the full schema which may include descriptions?  If a schema description is updated, will be ignored with patch?

**Comment by byapparov** [comment]
@dankruse1 description of the field and any nested field details will be ignored now.

**Comment by byapparov** [comment]
@dankruse1 Can you try it out in your code to see if it solves your problem, so we can get all the tests and field descriptions back in commercer.

**Comment by dankruse1** [comment]
@byapparov will do

**Pull request merged**
